import type { Metadata } from 'next'
import { Roboto_Condensed } from 'next/font/google'
import './globals.css'
import { Footer, Header } from '@/components'

const roboto = Roboto_Condensed({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${roboto.className} bg-white`}>
        <Header />
        <main className='min-h-[calc(100vh-78px-56px)]'>{children}</main>
        <Footer />
      </body>
    </html>
  )
}
