import type { Metadata } from 'next'
import { Footer, Header } from '@/components'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <>
      <Header />
      <main className='min-h-[calc(100vh-78px-56px)]'>{children}</main>
      <Footer />
    </>
  )
}
